version: "3"
services:
  react-app:
    image: gargp1065/majorproject:client2
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: gargp1065/majorproject:server2
    ports:
      - "3001:3001"
    networks:
      - mern-app
    volumes:
      - ./logs/access.log:usr/src/app/access.log
networks:
  mern-app:
    driver: bridge
