version: "3"
services:
  react-app:
    stdin_open: true
    image: gargp1065/majorproject:client2
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: gargp1065/majorproject:server2
    ports:
      - "3001:3001"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
