version: "3"
services:
  react-app:
    image: client:latest
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: server:latest
    ports:
      - "3001:3001"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge