---
- name: Pull docker image
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker front-end image
      shell: docker pull gargp1065/majorproject:client2

    - name: pull docker server image
      shell: docker pull gargp1065/majorproject:server2

    - name: docker-compose up
      shell: docker-compose -f docker-compose.yml up 

