---
- name: Pull docker image
  hosts: all
  tasks:
    - name: askldfal
      copy: 
        src: ./docker-compose.yml
        dest: ./

    - name: Start docker service
      service:
        name: docker
        state: started

    # - name: pull docker front-end image
    #   shell: docker pull gargp1065/majorproject:client2

    # - name: pull docker server image
    #   shell: docker pull gargp1065/majorproject:server2

    - name: lfdh
      command: docker-compose pull


    - name: stop previous back-end container
      shell: docker rm -f gargp1065/majorproject:server2

    - name: stop previous front-end container
      shell: docker rm -f gargp1065/majorproject:client2


    - name: running docker compose file
      shell: docker-compose up -d

